export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_REDIRECT = "PURCHASE_REDIRECT";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const SET_STATE_ERROR = "SET_STATE_ERROR";

export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";

export const SUBMIT_AUTH_START = "SUBMIT_AUTH_START";
export const SUBMIT_AUTH_SUCCESS = "SUBMIT_AUTH_SUCCESS";
export const SUBMIT_AUTH_FAIL = "SUBMIT_AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const DELETE_ORDER_START = "DELETE_ORDER_START";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";

export const INIT_INGREDIENTS = "INIT_INGREDIENTS";

export const PURCHASE_BURGER = "PURCHASE_BURGER";
export const FETCH_ORDERS = "FETCH_ORDERS";
